name: Python Musixmatch

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.6

    - name: Install poetry
      uses: snok/install-poetry@v1.2.0
      with:
        version: 1.1.8
        virtualenvs-create: false
        virtualenvs-in-project: false

    - name: Install dependencies
      run: poetry install

    - name: Outdated dependencies
      run: poetry show -o

    - name: Run Tests
      run: |
        make dev
